### ISSUE TITLE
Pass GITHUB_TOKEN as environmnet variable instead of cmd arg

### ISSUE THREAD

**Issue by behnazh-w** [oracle-samples/macaron#199]
- [x] We shouldn't pass the `GITHUB_TOKEN` as cmd arg because it can be logged and potentially leak info.
- [x] Also, it should be used as required argument for `analyze` action,

**Comment by tromai** [comment]
> Also, it should be used as required argument for analyze action,

If I understand it correctly, it means that we check for the existence of the token via [os.environ](https://docs.python.org/3/library/os.html#os.environ), if it does not exist, we terminate the program.

**Comment by behnazh-w** [comment]
> If I understand it correctly, it means that we check for the existence of the token via [os.environ](https://docs.python.org/3/library/os.html#os.environ), if it does not exist, we terminate the program.

@tromai Yes that's correct. I will assign the ticket to you.
