### ISSUE TITLE
Improve cmdLine usability by prompting on missing arguments

### ISSUE THREAD

**Issue by vinkris01** [oracle-samples/macaron#200]
Macaron currently prints out the same help text regardless of contextualising what the user provides as arguments. Consider making the error messages more suggestive so that it aids feature discovery and learning.
For e.g. 
Instead of 
_Missing parameters._

consider making the missing parameters message  more suggestive to hint at what's missing.
e.g. _Missing parameters. Provide path to remote (-R/--repo-url REPO_URL) or local repo ( -L/--local-repos-path)._

**Comment by nathanwn** [comment]
The `argparse` argument parser takes care of this out-of-the-box as long as we define which arguments are required correctly.
I will move this issue to the #211 thread and note it as "Check for any required arguments that are not correctly marked as `required=True` in the `argparse` argument parser".
