### ISSUE TITLE
Sphinx ^= 6.1.0 couldn't build our documentation

### ISSUE THREAD

**Issue by tromai** [oracle-samples/macaron#58]
**Description**
In the latest version of Sphinx (from [6.1.0](https://www.sphinx-doc.org/en/master/changes.html#release-6-1-0-released-jan-05-2023) to [6.1.3.](https://www.sphinx-doc.org/en/master/changes.html#release-6-1-3-released-jan-10-2023)), there is a breaking change that prevent the Macaron's documentation from being built successfully.
When building the documentation with `make clean docs`, there following error messages is seen (some part of the message is removed for visibility):
```
Running Sphinx v6.1.0
making output directory... done
[autosummary] generating autosummary for: "***"
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 18 source files that are out of date
updating environment: [new config] 18 added, 0 changed, 0 removed
ERROR: [numpydoc] While processing docstring for 'macaron.code_analyzer.call_graph.Node'                                                                                                            

Extension error (numpydoc.numpydoc):
Handler <function mangle_docstrings at 0x7fbe18f79d00> for event 'autodoc-process-docstring' threw an exception (exception: Expected a class or None, but got ~Node)
make[1]: *** [Makefile:23: html] Error 2
make[1]: Leaving directory '***'
make: *** [Makefile:230: docs/_build/html/index.html] Error 2
```
The message indicates that the error happened for the global variable [here](https://github.com/oracle-samples/macaron/blob/babd2e784fcea81ed6b383ad3ad992f9d6ab8cc7/src/macaron/code_analyzer/call_graph.py#L9).

**Solution**
- We could revert the version of Sphinx back to 6.0.0 so that the error won't happen.

**Comment by behnazh-w** [comment]
>We could revert the version of Sphinx back to 6.0.0 so that the error won't happen.

I prefer to change the docs to pass the build instead of pinning the version.

**Comment by tromai** [comment]
A quick look at the Sphinx GitHub[ repo](https://github.com/sphinx-doc/sphinx/) does not show any existing issue similar to us.

**Comment by tromai** [comment]
I will close this issue as the Sphinx documentation can now build normally without any error. However, there is still a warning as documented in #84
